/* Replace with your SQL commands */

CREATE TABLE IF NOT EXISTS `conversations` (
  id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
  context TEXT,
  model VARCHAR(125),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
